Update main workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,7 +2,7 @@ name: Build and Test
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
 
 jobs:
   build-and-test:
@@ -23,12 +23,10 @@ jobs:
 
       - name: Run the application (optional)
         run: node index.js
-      - name: Check if application is running
-        run: |
           if [ "${{ steps.run_application.outputs.app_status }}" == "success" ]; then
-            echo "Application is running successfully on port 3000."
-            exit 0
+          echo "Application is running successfully on port 3000."
+          exit 0
           else
-            echo "Application failed to start."
-            exit 1
+          echo "Application failed to start."
+          exit 1
           fi
